0-custom_http_response_header file

diff --git a/0x0F-load_balancer/0-custom_http_response_header b/0x0F-load_balancer/0-custom_http_response_header
--- a/0x0F-load_balancer/0-custom_http_response_header
+++ b/0x0F-load_balancer/0-custom_http_response_header
@@ -1,38 +1,79 @@
 #!/usr/bin/env bash
-# Installs Nginx with the following configurations:
-#Listens on port 80.
-#Returns a page containing "Hello World" when queried
-#at the root with a curl GET request.
-#Configures /redirect_me as a "301 Moved Permanently".
-#Includes a custom 404 page containing "Ceci n'est pas une page"
-#Contains a custom HTTP header named X-Served-By.
-#The value of the HTTP header is the hostname of the running server.
+# Duplicating web-01 to web-02
 
-apt-get update
-apt-get install -y nginx
+# To the the script run in action, uncomment the line below
+#set -x
 
-mkdir -p /var/www/html
-touch /var/www/html/index.html
-echo "Hello World" > /var/www/html/index.html
-touch /var/www/html/404.html
-echo "Ceci n'est pas une page" > /var/www/html/404.html
+function install() {
+	command -v "$1" &> /dev/null
 
-printf %s "server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-    add_header X-Served-By $HOSTNAME;
-    root   /var/www/html;
-    index  index.html index.htm;
+	# Shellcheck disable=SC2181
+	if [ $? -ne 0 ]; then
+		echo -e "	Installing: $1$\n"
+		sudo apt-get update -y -qq && \
+			sudo apt-get install -y "$1" -qq
+		echo -e "\n"
+	else
+		echo -e "	${1} is already installed.\n"
+	fi
+}
 
-    location /redirect_me {
-        return 301 http://cuberule.com/;
-    }
+install nginx
 
-    error_page 404 /404.html;
-    location /404 {
-      root /var/www/html;
-      internal;
-    }
-}" > /etc/nginx/sites-available/default
+# Allowing Nginx through firewall
+sudo ufw allow 'Nginx HTTP'
 
-service nginx restart
+# Giving user ownership to website files for easy editing
+if [ -d "/var/www" ]; then
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+else
+	sudo mkdir -p /var/www
+	sudo chown -R "$USER":"$USER" /var/www
+	sudo chmod -R 755 /var/www
+fi
+
+# Creating directories if they are not present
+for directory in /var/www/{html,error}; do
+	if ! [ -d "$directory" ]; then
+		mkdir -p "$directory"
+	fi
+done
+
+# Creating new index.html
+echo "Hello World!" > /var/www/html/index.html
+
+# Creating a new error page
+echo "Ceci n'est pas une page" > /var/www/html/error_404.html
+
+# Backing up default server config files
+sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup
+
+server_config=\
+"server {
+		listen 80 default_server;
+		listen [::]:80 default_server;
+		root /var/www/html;
+		index index.html index.htm index.nginx-debian.html
+		server_name_;
+		add_header X-Served-By \$hostname;
+		location / {
+			try_files \$uri \$uri/ =404;
+		}
+		if (\$request_filename ~ redirect_me){
+			rewrite ^ https://th3-gr00t.tk/ permanent;
+		}
+		error_page 404 /error_404.html;
+		location = /error_404.html {
+			internal;
+		}
+}"
+
+#shellcheck disable=SC2154
+echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default
+
+if [ "$(pgrep -c nginx)" -le 0 ]; then
+	sudo service nginx start
+else
+	sudo service nginx restart
+fi
